CREATE TABLE NguoiDung (
    Id INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL UNIQUE,
    MatKhau VARCHAR(256) NOT NULL,
    Salt VARCHAR(64) NOT NULL,
    VaiTro VARCHAR(20) NOT NULL DEFAULT 'Member',
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'HoatDong',
    NgayTao DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE DanhMuc (
    Id INT PRIMARY KEY IDENTITY(1,1),
    TenDanhMuc NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(500)
);

CREATE TABLE LehHoi (
    Id INT PRIMARY KEY IDENTITY(1,1),
    DanhMucId INT NOT NULL REFERENCES DanhMuc(Id),
    TenLehHoi NVARCHAR(200) NOT NULL,
    TomTat NVARCHAR(500),
    MoTa NVARCHAR(MAX),
    YNghiaVanHoa NVARCHAR(MAX),
    NgayBatDau DATE,
    NgayKetThuc DATE,
    DiaDiem NVARCHAR(200),
    TinhThanh NVARCHAR(100),
    AnhDaiDien VARCHAR(500),
    IsDeleted BIT NOT NULL DEFAULT 0,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NguoiTaoId INT REFERENCES NguoiDung(Id),
    CONSTRAINT CHK_LehHoi_Ngay CHECK (NgayKetThuc IS NULL OR NgayBatDau IS NULL OR NgayKetThuc >= NgayBatDau)
);

CREATE TABLE HinhAnh (
    Id INT PRIMARY KEY IDENTITY(1,1),
    LehHoiId INT NOT NULL REFERENCES LehHoi(Id),
    DuongDan VARCHAR(500) NOT NULL,
    MoTa NVARCHAR(200),
    LaDaiDien BIT NOT NULL DEFAULT 0,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE BaiViet (
    Id INT PRIMARY KEY IDENTITY(1,1),
    TieuDe NVARCHAR(300) NOT NULL,
    TomTat NVARCHAR(500),
    NoiDung NVARCHAR(MAX),
    AnhDaiDien VARCHAR(500),
    NguoiTaoId INT REFERENCES NguoiDung(Id),
    IsDeleted BIT NOT NULL DEFAULT 0,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE LehHoi_BaiViet (
    LehHoiId INT NOT NULL REFERENCES LehHoi(Id),
    BaiVietId INT NOT NULL REFERENCES BaiViet(Id),
    PRIMARY KEY (LehHoiId, BaiVietId)
);

CREATE TABLE BinhLuan (
    Id INT PRIMARY KEY IDENTITY(1,1),
    NguoiDungId INT NOT NULL REFERENCES NguoiDung(Id),
    LehHoiId INT REFERENCES LehHoi(Id),
    BaiVietId INT REFERENCES BaiViet(Id),
    NoiDung NVARCHAR(500) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'ChoDuyet',
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT CHK_BinhLuan_Target CHECK (
        (LehHoiId IS NOT NULL AND BaiVietId IS NULL) OR
        (LehHoiId IS NULL AND BaiVietId IS NOT NULL)
    )
);

CREATE TABLE ResetPasswordToken (
    Id INT PRIMARY KEY IDENTITY(1,1),
    NguoiDungId INT NOT NULL REFERENCES NguoiDung(Id),
    Token VARCHAR(128) NOT NULL UNIQUE,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayHetHan DATETIME NOT NULL,
    DaSuDung BIT NOT NULL DEFAULT 0
);
